#!/bin/bash
export JAVA_HOME=/usr/bin/java/

case $1 in
   start)
     echo "Starting dsqd" >> /var/log/engineyard/dsqd/dsqd.log
     echo $$ > /var/run/dsqd.pid
     cd /data/javaserver
     exec 2>&1 java -jar -Xmx350m dsqd.jar >> /var/log/engineyard/dsqd/dsqd.log 
     ;;									     
   stop) 
     echo "Stopping dsqd" >> /var/log/engineyard/dsqd/dsqd.log
     kill `cat /var/run/dsqd.pid` 
     ;;								             
   *)  
echo "usage: xyz {start|stop}" ;;
esac

